version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_jornada
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: control_jornada
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_jornada
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pgdata:
  mongo_data:
