version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_jornada
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: control_jornada
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
