services:
  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./server/.env.docker
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    container_name: postgres_jornada
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: control_jl
    volumes:
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_jornada
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  pgdata:
  mongo_data:
